import { readFileSync } from "node:fs";
import { join } from "node:path";

/**
 * Read the palette out of the stylesheet at build time.
 *
 * The social card is generated by Satori, which cannot resolve CSS custom
 * properties, so it needs literal colours. Hardcoding them is how the card
 * silently drifts from the site: the first version of this file carried an
 * fg-3 value that was already stale within the hour. Reading the tokens keeps
 * `globals.css` the only place a colour is defined.
 *
 * Node-only, and safe here because every route in this project is prerendered.
 */
export type Palette = Record<string, string>;

export function palette(): Palette {
  const css = readFileSync(join(process.cwd(), "src/app/globals.css"), "utf8");
  const tokens = Object.fromEntries(
    [...css.matchAll(/--color-([a-z0-9-]+):\s*(#[0-9a-fA-F]{6})/g)].map((m) => [m[1], m[2]]),
  );

  if (Object.keys(tokens).length === 0) {
    throw new Error("No --color-* tokens found in globals.css. Has the token layer moved?");
  }

  return tokens;
}

/** Look a token up, failing loudly rather than rendering an undefined colour. */
export function token(p: Palette, name: string): string {
  const value = p[name];
  if (!value) throw new Error(`Unknown colour token: ${name}`);
  return value;
}
